apiVersion: apps.open-cluster-management.io/v1
kind: HelmRelease
metadata:
  name: nginx-app
  namespace: default
repo:
  chartName: nginx-chart
  source:
    git:
      branch: main
      chartPath: nginx-app/nginx-chart
      urls:
      - https://github.com/mikeshng/sample-helmrelease.git
    type: git
  version: 0.1.0
spec:
  serviceAccount:
    name: nginx-app-sa

